### PR TITLE
Mouse handling form

### PR DESCRIPTION
**Pull request by david-roper**
version 1.0 of the mouse handling form

closes issue #7 

form seen [here](https://playground.opendatacapture.org/?files=NobwRAxg9gdgLgU3mAXGA9AKgAQIM4A2AlvALQAmReAhgEYELYAOCATgGYIRxGxVzo8UVnFJRaAKy5w82TOgA6MJdBh442ENnIJ2JBAEk1cVgFcAtkg0BfbAF5s1AO7UiGouabC4ACgDk6GbwHgjoAG4AjOhQLDDk1HDUENRMcKasCAACEQB0AAz56NAZORJ4fgCUANwqsOqa2ABe2LYOzq7unt7%2BgabBluFRjVDkmQDMOQBMEwBs6CQ6AB6l5dVKSgiLXiLautSmBBo6ejCGxmaW8D4gStjYANYLKNh%2BAGIA8gBKALJ%2BADS3bAEagwADmpmooIQzz8SH%2BgMSoLwz2AfgAEiDyMQwf8-ABhUxMJgkUG4gAqrFcMBJfgAugCYHcSIhWDBqARnjdGXdcJQeLBnhEGTzsGzLDDvu8AKoAZQAogB9NEAQQAcgARAAyBlVAHEFR8fn5AdZhdhVIh4JzAXdWFAoOZVRZaGxrdyRY84jD1KwaWaRWFqL6QXBngowCQmKY4OH-TzgS6Odhw597eZRc62OGbS04wALTHY0FkgCeLDdIrunvI3pMfpzd0DwatybAlMoUFjDaBdAQSfDr2E6ag7GwBbiRa77p5MX5agrlbu4bJrgI2FBlNotBJ4bDYBXRDXG7o27BU8XS7ABKJO9QrevxLPYDjIuXphd2EscDzI13rbJ76MF%2BP7kNm053NYOamjm45YiS6rpAkvAwAuHpPK2MCZqw56Vk2RAhnukbRjhIoJn2e4IZSc7YD45gkNG%2BAVGBIqQdy0HcjoiSHsimg5joeAQL6qTITC6r4IJRAurITh5kgjiMiCHjstgLiyLBDDkH82BuLIEDpBk8BjoWJLYHg%2BB4MhWmYtg36MOpJnASM2CmGZ5A5PC074Dw5gJAg5CUUhArYEKOYkD6pjcMhPGogACgw1BmdgegEGuUDRjZeZUElQ7YLAECMNQn5pYlJxULJsiFfZYKmeZyE5NglEmZVxnVWZeAWbA2jUCWGVZewOVZZsLDcH5NlQNosAFWNiSpaO34ZIw3n4NlrC4EkebaXERBhEQ5AQmubUdYy0CeAwiBudgyopSt5iyCORkTiZLmjbQPW2Q9WJsI4GSONdQ3SKNcDjR%2BThuJljLvTK7wxXScbEPlajQi8UqqtqeJyqq8rqh5Io8HADASsVjAYo91WDqw5jGmxZqWAl6T4Kh2B2g6TrmC6rCM1W6F%2BKo6g45WZH9mAqYOhmbNZs%2B3YZOwe7M46WHMTy7GVlVxZlkjXKLtWMK83A-Okb2Qvk8Oo6qyRPLS3uquliwisQfmLWggFc6cw83O6-r8aGxRiHUbR9GIHgTGS%2BBTO6FbjvO8hdstCaZqBsQ8RzjKECyT5zyNDk4hSNw1w5nLrPsxnOQ%2BiSPgVA7pNq%2BWTQl3WYLl5XcFglHQWZ5h4usOXJpMTA1hrDAz5gGKCCoBGcSbDkMhgNYtJAA&label=LIewrgzgpg%2BgEgQwHYBMA2BLJBzGAxEAJwFsg)

### CODE REVIEW

**Comment by gdevenyi** [comment]
What is handling session?

Since the data here is longitudinal/time logged, shouldn't that be automatically handled?

**Review by gdevenyi — CHANGES_REQUESTED** [review]
I don't think Handling Session needs to be logged?

**Comment by david-roper** [comment]
Handling sessions are done to acclimate the mouse before going throughs experiment that require them to be moved by hand often.  Since multiple session happen in one day, I guess the user could just fill in the form multiple times.

**Comment by gdevenyi** [comment]
> Handling sessions are done to acclimate the mouse before going throughs experiment that require them to be moved by hand often. Since multiple session happen in one day, I guess the user could just fill in the form multiple times.

Yes, this is the correct way.

**Review by gdevenyi — APPROVED** [review]

**Pull request merged**
